### ISSUE TITLE
Learn IDE

### ISSUE THREAD

**Issue by amjack59** [learn-co-curriculum/other-hash-methods-code-along#23]
Hello, I am having more problems with the learn IDE. I have raised this issue previously and this is just a further update into the difficulties I am having now. I am currently in the "other-hash-methods-code-along" . I opened my IDE locally (manually, because I can no longer just click the OPEN button on the learn.co lab page and have it fork, clone, and open the IDE as it used to do) then clicked the OPEN button to get my lab to fork and clone so I can complete the lab. The problem is, that it does not show up in the IDE file tree on the left. It does show in the command line portion on the bottom of the IDE and when I cd into the code/labs directory it shows up there. Problem is that I cannot access it in the file tree to open the files in the editor to work on them. Very frustrating that this is an ongoing issue. I have temporarily created a local library on my desktop to manually fork and clone the labs to my computer and then will use the manual method to add, commit, and push. But if I cannot use the learn IDE then the testing of the labs becomes problematic. Please help.

**Comment by AnnJohn** [comment]
hi @amjack59 sorry for the issues that you're having. We use this space for issues specifically related to curriculum content. Since the IDE problems are product issues, you will need to file a bug report (if you hover over your profile pic in Learn you'll see a menu pop up with an option to report a bug) or email support+ide@learn.co or use the Ask a Question tool for live support from someone from our Learn Expert team. Thanks!
